### PR TITLE
Change ChainID width to 64 bit

### PR DESCRIPTION
**Pull request by gumb0**
https://github.com/ethereum/EIPs/pull/2263

### CODE REVIEW

**Comment by gumb0** [comment]
Rebased.

**Comment by chfast** [comment]
Can this be closed now?

**Comment by gumb0** [comment]
Well there's a separate EIP for this now https://github.com/ethereum/EIPs/issues/2294

It might or might not be included in Berlin :man_shrugging:

**Comment by chfast** [comment]
Can we close this now? The 256-bit variant is the current EIP spec.

**Comment by axic** [comment]
We actually still want to apply this through EIP-1985.

**Comment by chfast** [comment]
> We actually still want to apply this through EIP-1985.

Right, but the change is trivial. I don't think it's worth to keep the PR open. But we can still link to it from the EIP.

**Pull request closed without merging**
