### PR TITLE
Fall back to evmc_create in the loader as a last resort

### LINKED ISSUE #79: Loader should also look for "evmc_create" without library postfix

### PR DESCRIPTION
**Pull request by axic**
Fixes #79.

### CODE REVIEW

**Comment by axic** [comment]
Needs tests.

**Comment by chfast** [comment]
How quickly this is needed?

**Comment by axic** [comment]
No time pressure, unless you mean delaying it weeks/months.

**Comment by chfast** [comment]
You have to approve it.

**Comment by axic** [comment]
I cannot since it is my PR.

**Pull request merged**
