### PR TITLE
rust: add enum aliases

### PR DESCRIPTION
**Pull request by axic**
Part of #168.

### CODE REVIEW

**Comment by jakelang** [comment]
needs rebase.

**Comment by axic** [comment]
It turns out supporting enum type aliases properly was only merged into rustc on 19th Jan: https://github.com/rust-lang/rust/pull/56225

**Comment by axic** [comment]
Wow, apparently this is coming in rustc 1.37: https://github.com/rust-lang/rust/pull/61682

**Comment by axic** [comment]
Woohoo, 1.37 was released.

**Pull request merged**
