### PR TITLE
 Add C++ wrappers/bindings for VM

### PR DESCRIPTION
**Pull request by chfast**
Part of #156.

### CODE REVIEW

**Comment by axic** [comment]
@chfast do we want to finish/merge this for 6.1.0 or should 6.1.0 be released sooner?

**Comment by chfast** [comment]
> do we want to finish/merge this for 6.1.0 or should 6.1.0 be released sooner?

Can be either way. I had some spare time to handle this part. Bigger part is to create the Host interface, but also can be done maybe this week.

**Comment by axic** [comment]
@chfast it is up to you, I'm fine merging this or not merging this for this release. Would be nice to make the release very soon though.

**Comment by chfast** [comment]
We should at least merge this one.

**Pull request merged**
