### PR TITLE
Upgrade Cable to 0.4.4

### PR DESCRIPTION
**Pull request by chfast**
Fixes CMake issue in https://github.com/ewasm/hera/pull/550.

### CODE REVIEW

**Comment by axic** [comment]
Apparently this isn't the solution. Hera throws this:
```
CMake Error at cmake/cable/CableBuildType.cmake:14 (message):
  cable_set_build_type() can be used before project()
Call Stack (most recent call first):
  CMakeLists.txt:24 (cable_set_build_type)
```

**Comment by chfast** [comment]
> Apparently this isn't the solution. Hera throws this:
> 
> ```
> CMake Error at cmake/cable/CableBuildType.cmake:14 (message):
>   cable_set_build_type() can be used before project()
> Call Stack (most recent call first):
>   CMakeLists.txt:24 (cable_set_build_type)
> ```
> 
> If I move `cable_set_build_type` prior to `project` then it works, so I guess it is an okay enough work around.

Works for me. Are you sure you have not upgraded Cable in Hera?

**Comment by axic** [comment]
> Are you sure you have not upgraded Cable in Hera?

It seems I did change it locally. Did a fresh checkout and now it works.

**Comment by chfast** [comment]
> It seems I did change it locally. Did a fresh checkout and now it works.

I pushed it to https://github.com/ewasm/hera/pull/550 to check.

**Pull request merged**
