### PR TITLE
cpp: Rename evmc::vm to evmc::VM

### LINKED ISSUE #249: C++: Rename evmc::vm to evmc::VM
In `evmc.hpp`, in namespace `evmc`, rename:
- `vm` to `VM`,
- `result` to `Result`.

### PR DESCRIPTION
**Pull request by chfast**
Closes #249

### CODE REVIEW

**Comment by axic** [comment]
Was this introduced in this release or is this a breaking change?

The rest of the C++ interfaces are camel cased so this is consistent with it, with one exception: `result`. Would changing that to `Result` be breaking?

**Comment by chfast** [comment]
Nothing strict here, but have a feeling that types representing OOP classes should have camel case names. The `result` was left because it's more like `unique_ptr` but can be renamed as well.

The `vm` class was added in 6.2. I have to check the `result`.

**Comment by chfast** [comment]
Both were added in 6.1: https://github.com/ethereum/evmc/blob/v6.1.1/include/evmc/evmc.hpp.

**Comment by axic** [comment]
@chfast reviving?

**Comment by axic** [comment]
@chfast will `Result` handled in a separate PR?

**Comment by chfast** [comment]
> @chfast will `Result` handled in a separate PR?

I'm not sure about `result`. It is rather a value type (like `string`).

**Pull request merged**
