### PR TITLE
Add clang-format config

### PR DESCRIPTION
**Pull request by chfast**
@axic are you fine with using clang-format config from cpp-ethereum / ethminer?

### CODE REVIEW

**Comment by axic** [comment]
I think it looks horrible in `cpp-ethereum`, but hopefully it doesn't distort the header too much?

Can you run a reformatting here? I actually very much do not like the partial reformatting done in cpp-ethereum and since this project is tiny, I'd just reformat it at in this PR.

**Comment by chfast** [comment]
What exactly looks horrible?
We can stick to 80 column limit if preferred.

**Comment by axic** [comment]
The way parameters and arguments are laid out, especially that the closing parenthesis is not on a new line :)

**Comment by axic** [comment]
Also need to reformat the example files.

**Comment by chfast** [comment]
> The way parameters and arguments are laid out, especially that the closing parenthesis is not on a new line :)

clang-format does not support this, but you can send a patch to clang-format.

**Comment by chfast** [comment]
Updated.

**Comment by chfast** [comment]
Can I merge it?

**Pull request merged**
