### PR TITLE
VM Tester tool

### PR DESCRIPTION
**Pull request by chfast**
Ready, but some git history cleanup might be needed.

Depends on #11.

### CODE REVIEW

**Comment by axic** [comment]
Can hunter and boost be disabled if the project pulling this in only uses the header file?

**Comment by chfast** [comment]
1. Boost and GTest are going to be downloaded only if `EVMC_BUILD_TEST=ON`.
2. Hunter can be additionally disabled with `HUNTER_ENABLED=OFF`.

**Comment by chfast** [comment]
BTW I have to improve command line options handling in vmtester.

Also, how about naming everything with `evmc-` prefix? I.e. `evmc-vmtester` and `evmc-examplevm`?

**Comment by axic** [comment]
> Also, how about naming everything with evmc- prefix? I.e. evmc-vmtester and evmc-examplevm?

Sounds good.

**Comment by chfast** [comment]
Ready?

**Comment by axic** [comment]
> Boost and GTest are going to be downloaded only if EVMC_BUILD_TEST=ON.

I really hope that's true, because with my limited understanding of cmake it seems to show the contrary. The `HunterGate` command seems to be outside that `if`.

**Comment by axic** [comment]
Can you document that in the README for other implementers?

**Comment by chfast** [comment]
How about I make also Hunter to be off by default add install rule for the evmc.h header and document CMake options in another PR?

**Comment by chfast** [comment]
I did a bit more experiments with CMake. `HunterGate` is only a declaration and does not init Huter. Hunter is initialized when used first time, what is only when building with `-DEVMC_BUILD_TESTS=ON`. I added a comment about it.

**Comment by axic** [comment]
> Document what? CMake options?

Yep, how to turn off hunter and tests.

**Comment by chfast** [comment]
> > Document what? CMake options?
> 
> Yep, how to turn off hunter and tests.

They are off by default.

**Pull request merged**
