### PR TITLE
test: Test compilation without exceptions

### PR DESCRIPTION
**Pull request by chfast**

### CODE REVIEW

**Review by axic — COMMENTED** [review]
Why does this compile before merging the hex noexcept changes?

**Comment by chfast** [comment]
> Why does this compile before merging the hex noexcept changes?

Ha, good question. It is because the `evmc::hex` is still implemented in side `hex.cpp` file.

I'm not sure this is any good test. I was using it while reworking hex do I decided to drop it anyway. The full no-exception build should be better.

**Comment by chfast** [comment]
Now it makes more sense.

**Review by axic — APPROVED** [review]
Though it was never verified why this worked before merging #643 ?

**Pull request merged**
