### PR TITLE
EVMC Example VM

### PR DESCRIPTION
**Pull request by chfast**
This refactors evmc-examplevm. On CI examplevm is build as a shared library and tested with vmtester.

### CODE REVIEW

**Comment by axic** [comment]
This PR does a lot of reformatting before merging clang-format? 😉

**Comment by chfast** [comment]
> This PR does a lot of reformatting before merging clang-format? :wink:
Yes. I reformatted examplevm.cpp.

**Comment by chfast** [comment]
Is this a problem?

**Comment by axic** [comment]
I guess there will be no change to the clang-format anyway (😢), but still looks better to have the formatting on its own.

**Comment by chfast** [comment]
We consider some changes, but you have to propose them as a .clang-format change. Not in natural language.

**Pull request merged**
