### PR TITLE
Rename destination -> recipient

### PR DESCRIPTION
**Pull request by chfast**

### CODE REVIEW

**Comment by yperbasis** [comment]
@chfast Shouldn't this merge be into the master branch?

**Comment by chfast** [comment]
> @chfast Shouldn't this merge be into the master branch?

This mean it should land after #615.

**Comment by yperbasis** [comment]
It's better to do the renaming in bindings/java/java/src/test/java/org/ethereum/evmc/TestMessage.java & EvmcTest.java as well.

**Review by yperbasis — APPROVED** [review]

**Comment by chfast** [comment]
Should we test this in any downstream project? May be annoying in evmone's unit tests.

**Comment by chfast** [comment]
I checked the change in evmone, and all required modification in evmone are purely mechanical.

**Pull request merged**
