### PR TITLE
Add LLVM sanitizers to Rust CI

### PR DESCRIPTION
**Pull request by jakelang**
depends: #314

### CODE REVIEW

**Comment by chfast** [comment]
Add `ln -s /usr/bin/llvm-symbolizer-3.8 /usr/bin/llvm-symbolizer`.

**Comment by chfast** [comment]
You can combine leak and memory sanitizers: https://clang.llvm.org/docs/LeakSanitizer.html#usage.

**Comment by jakelang** [comment]
Tests which leak:
- `from_ffi`: 16 bytes
- `get_code_size`: 96 bytes
- `execution_context`: 2x 96 bytes

**Comment by jakelang** [comment]
@chfast it seems that rust does not accept multiple sanitizers at once :(
```
error: failed to run `rustc` to learn about target-specific information

Caused by:
  process didn't exit successfully: `rustc - --crate-name ___ --print=file-names -Z sanitizer=address,leak --target x86_64-unknown-linux-gnu --crate-type bin --crate-type rlib --crate-type dylib --crate-type cdylib --crate-type staticlib --crate-type proc-macro` (exit code: 1)
--- stderr
error: incorrect value `address,leak` for debugging option `sanitizer` - one of: `address`, `leak`, `memory` or `thread` was expected
```

**Comment by chfast** [comment]
@jakelang RTFM.

> LeakSanitizer is supported on x86_64 Linux and macOS. In order to use it, simply build your program with AddressSanitizer:

You build it with `sanitize=address` and set env var `ASAN_OPTIONS=detect_leaks=1.

**Comment by jakelang** [comment]
Ah I see, thx

**Comment by axic** [comment]
@jakelang @chfast merged #314, rebased this, but it fails on linking asan. Can you check?

**Comment by axic** [comment]
Solving asan for vmtester+rust seems to be a bit more tricky. However it works with cargo test, so merging that first.

**Pull request merged**
